class DetectionConfig:
    YOLO_CONF_THRESHOLD = 0.25
    BOX_PADDING_PX = 5
    MERGE_X_MARGIN_PX = 12
    MERGE_Y_MARGIN_PX = 0
    MERGE_VERTICAL_OVERLAP_RATIO = 0.60

class InpaintConfig:
    LAMA_INPUT_SIZE = 512
    MAX_BOX_SIZE = 400
    CONTEXT_MARGIN_PX = 56
    TELEA_RADIUS = 7
    ALPHA_BLUR_KERNEL = (3, 3)

class MaskConfig:
    DILATE_KERNEL_SIZE = (5, 5)
    DILATE_ITERATIONS = 3
    BG_DILATE_KERNEL_SIZE = (9, 9)
    BUBBLE_WHITE_RATIO_THRESHOLD = 0.85
    BUBBLE_BLACK_RATIO_THRESHOLD = 0.85
    NOISY_EDGE_RATIO_THRESHOLD = 0.01
    NOISY_STD_THRESHOLD = 20.0
    LOW_CONTRAST_THRESHOLD = 80.0
    DARK_BG_RATIO_THRESHOLD = 0.5
    DARK_BG_DILATE_KERNEL = (7, 7)
    DARK_BG_DILATE_ITERATIONS = 2

class AppCacheConfig:
    MAX_IMAGES_IN_RAM = 20
    MAX_PIXMAPS_IN_RAM = 6
    MAX_HISTORY_IN_RAM = 20
